server.port=8080
spring.application.name=smart-expense-tracker-api
storage.file.path=data/expenses.json

# OpenAPI Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
