version: '3.8'

services:
  expense-tracker-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-expense-tracker-api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - STORAGE_FILE_PATH=data/expenses.json
    restart: unless-stopped
